### ISSUE TITLE
Allow specifying middleware "globally"

### ISSUE THREAD

**Issue by aisrael** [crystal-community/cossack#15]
Hi! Is there a way to specify Cossack Middleware to inject to every Cossack client?

Use cases:

1. Specify Proxy Middleware (when it's implemented) once at application startup
2. Potentially create a VCR-like middleware that can be specified at `spec_helper.cr`

**Comment by greyblake** [comment]
If you mean an ability to inject it globally - once for all clients, then no, there is no way to do it.

**Comment by aisrael** [comment]
Is this something that the community might find useful, perhaps? Be happy to take a crack at it. I need it now (don't want to pollute production code with `if environment == "test"...`)

**Comment by aisrael** [comment]
Am thinking of something along these lines. In `spec_helper.cr`:

```
Cossack::Middleware.use CossackRecorderMiddleware
```

This way, the client code can keep using `Cossack::Client.new` as is, with no modifications, unaware of whether it's running in a test or in the actual environment.

WDYT?

**Comment by greyblake** [comment]
Sorry, I would not accept this.

The reason is, I don't think it's a good idea to rely on the global state, and allow to modify it (yea, even Crystal compiler allows it).

Imagine the following situation: you have your application Foo, that uses libraries Bar and Baz.
Bar and Baz depend on Cossack. Bar uses `Cossack::Middleware.use` to add some middleware. This may break Bar or add some weird side effect.

However, I am OK with implementing such middleware for a client instance.

If you need something like `Cossack::Middleware.use` you probably need to redesign your application, and create an instance of a client just in one place and inject it as a dependency to any other class/functions where you want to use it.
Then in your test you can substitute the client.

I hope it helps. Thanks.

**Comment by aisrael** [comment]
Yeah I'm trying not to pollute production code with "if running in test, then inject the recorder middleware". Anyway, I've realized that you can "reopen" and override library classes. Also, I've discovered [Hi8](https://github.com/vonKingsley/hi8.cr) that provides the transparent, VCR-like functionality am looking for.
